<a href="https://colab.research.google.com/github/zhi-yu-lin/data-and-python/blob/main/Project_2_Air_quality_mini_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Clean and wrangle air quality data

The following data file contains data collected at a roadside monitoring station.  You can see the data in a spreadsheet here: https://docs.google.com/spreadsheets/d/1XpAvrpuyMsKDO76EZ3kxuddBOu7cZX1Od4uEts14zco/edit?usp=sharing

The data contains:
* a heading line (Chatham Roadside) which needs to be skipped
* dates which are sometimes left- and sometimes right-justified indicating that they are not formatted as dates, rather they are text (so need to be converted to dates)
* times which are not all in the same format
* Nitrogen Dioxide levels which are, again, text and sometimes contain nodata
* Status which is always the same

### Project - clean, sort and wrangle the data

Read the dataset into a dataframe, skipping the first row   
Convert dates to date format  
Remove rows with nodata in the Nitrogen dioxide column  
Convert the Nitrogen dioxide levels values to float type  
Sort by Nitrogen dioxide level  
Create a new column for 'Weekdays' (use df['Date'].dt.weekday)  
Rename the column Nitrogen dioxide level to NO2 Level (V ug/m2)  
Remove the Status column  

The dataset can be viewed here:  https://drive.google.com/file/d/1aYmBf9il2dWA-EROvbYRCZ1rU2t7JwvJ/view?usp=sharing  and the data accessed here: https://drive.google.com/uc?id=1SOe9b4VJ1FCtDVgZ2T8d00-jTw2Kux1i  This is a .csv file  

**NOTE:** Some useful references are included at the bottom of this spreadsheet.

Use the code cell below to work your code.

In [36]:
from datetime import datetime
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scipy.stats

# Read the dataset into a dataframe, skipping the first row
url = 'https://drive.google.com/uc?id=1SOe9b4VJ1FCtDVgZ2T8d00-jTw2Kux1i'
df = pd.read_csv(url)
df.columns = df.iloc[0]
df = df.drop(0)
df.describe()
df.info()
df

# Convert dates to date format
df['Date'] = pd.to_datetime(df['Date'], format='%d/%m/%Y')

# Remove rows with nodata in the Nitrogen dioxide columnï¼› Convert the Nitrogen dioxide levels values to float type
df['Nitrogen dioxide'] = pd.to_numeric(df['Nitrogen dioxide'], errors='coerce')
df = df.dropna(subset = ['Nitrogen dioxide'])

# Sort by Nitrogen dioxide level
df = df.sort_values(by='Nitrogen dioxide', ascending = False)

# Create a new column for 'Weekdays'
df['Weekdays']= df['Date'].dt.weekday

# Rename the column Nitrogen dioxide level to NO2 Level (V ug/m2)
df.rename(columns={'Nitrogen dioxide': 'NO2 Level (V ug/m2)'}, inplace=True)

# Remove the Status column
df = df.drop(columns=['Status'])
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 1 to 8784
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date              8784 non-null   object
 1   Time              8784 non-null   object
 2   Nitrogen dioxide  8784 non-null   object
 3   Status            8784 non-null   object
dtypes: object(4)
memory usage: 274.6+ KB

0          Date   Time  NO2 Level (V ug/m2)  Weekdays
471  2020-01-20  15:00            113.06189         0
6210 2020-09-15  18:00             92.13063         1
6207 2020-09-15  15:00             87.96723         1
809  2020-02-03  17:00             87.10202         0
472  2020-01-20  16:00             84.86896         0
...         ...    ...                  ...       ...
8670 2020-12-27   6:00              0.65300         6
5715 2020-08-26   3:00              0.59123         2
4490 2020-07-06   2:00              0.58930         0
5713 2020-08-26   1:00              0.58689         2
8669 2020-12-27   5:00              0.42410         6

[8632 rows x 4 columns]

### Expand the dataset and show summary statistics for larger dataset
---

There is a second data set here covering the year 2021:  https://drive.google.com/uc?id=1aYmBf9il2dWA-EROvbYRCZ1rU2t7JwvJ  

Concatenate the two datasets to expand it to 2020 and 2021.  

Before you can concatenate the datasets you will need to clean and wrangle the second dataset in the same way as the first.  Use the code cell below.  Give the second dataset a different name.

After the datasets have been concatenated, group the data by Weekdays and show summary statistics by day of the week.

In [50]:
url_2 = 'https://drive.google.com/uc?id=1aYmBf9il2dWA-EROvbYRCZ1rU2t7JwvJ'
df_2 = pd.read_csv(url_2)
df_2.columns = df_2.iloc[0]
df_2 = df_2.drop(0)


df_2['Date'] = pd.to_datetime(df_2['Date'], format='%d/%m/%Y')
df_2['Weekdays']= df_2['Date'].dt.weekday

df_2 = df_2.sort_values(by='Nitrogen dioxide', ascending = False)

df_2.rename(columns={'Nitrogen dioxide': 'NO2 Level (V ug/m2)'}, inplace=True)
df_2 = df_2.drop(columns=['Status'])

df_con = pd.concat([df, df_2], ignore_index=True)
df_con

df_con.groupby('Weekdays').describe()

<ipython-input-50-0823a25eb0f5>:17: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  df_con.groupby('Weekdays').describe()
<ipython-input-50-0823a25eb0f5>:17: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  df_con.groupby('Weekdays').describe()
<ipython-input-50-0823a25eb0f5>:17: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  df_con.groupby('Weekdays').describe()
<ipython-input-50-0823a25eb0f5>:17: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  df_con.groupby('Weekdays').describe()
<ipython-input-50-0823a25eb0f5>:17: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  df_con.groupby('Weekdays').describe()
<ipython-input-50-0823a25eb0f5>:17: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  df_con.groupby('Weekdays').describe()
<ipython-input-50-0823a25eb0f5>:17: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  df_con.groupby('Weekdays').describe()

0         Date                                                        \
         count unique                  top freq                first
Weekdays
0         2466    104  2020-01-20 00:00:00   24  2020-01-06 00:00:00
1         2467    104  2020-09-15 00:00:00   24  2020-01-07 00:00:00
2         2510    105  2020-02-05 00:00:00   24  2020-01-01 00:00:00
3         2490    105  2020-02-06 00:00:00   24  2020-01-02 00:00:00
4         2501    105  2021-02-12 00:00:00   24  2020-01-03 00:00:00
5         2494    104  2020-01-18 00:00:00   24  2020-01-04 00:00:00
6         2464    104  2020-01-19 00:00:00   24  2020-01-05 00:00:00

0                              Time                                \
                         last count unique    top freq first last
Weekdays
0         2021-12-27 00:00:00  2466     34  11:00  104   NaN  NaN
1         2021-12-28 00:00:00  2467     34  18:00  104   NaN  NaN
2         2021-12-29 00:00:00  2510     34  16:00  105   NaN  NaN
3         2021-12-30 00:00:00  2490     34  22:00  104   NaN  NaN
4         2021-12-31 00:00:00  2501     34  19:00  105   NaN  NaN
5         2021-12-25 00:00:00  2494     34  20:00  104   NaN  NaN
6         2021-12-26 00:00:00  2464     34  21:00  103   NaN  NaN

0        NO2 Level (V ug/m2)
                       count unique       top freq first last
Weekdays
0                       2466   2450    nodata   14   NaN  NaN
1                       2467   2435    nodata   33   NaN  NaN
2                       2510   2480    nodata   25   NaN  NaN
3                       2490   2479    nodata    7   NaN  NaN
4                       2501   2498   8.98875    2   NaN  NaN
5                       2494   2490  12.55556    2   NaN  NaN
6                       2464   2456   1.33875    4   NaN  NaN

### Helpful references
---
Skipping rows when reading datasets:  
https://www.geeksforgeeks.org/how-to-skip-rows-while-reading-csv-file-using-pandas/  

Converting strings to dates:  
https://www.geeksforgeeks.org/convert-the-column-type-from-string-to-datetime-format-in-pandas-dataframe/

Dropping rows where data has a given value:  
https://www.datasciencemadesimple.com/drop-delete-rows-conditions-python-pandas/  
(see section Drop a row or observation by condition)

Convert a column of strings to a column of floats:
https://datatofish.com/convert-string-to-float-dataframe/  

Create a new column from data converted in an existing column:  
https://www.geeksforgeeks.org/create-a-new-column-in-pandas-dataframe-based-on-the-existing-columns/  

Rename a column:  
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rename.html  

Remove a column by name:  
https://www.kite.com/python/answers/how-to-delete-columns-from-a-pandas-%60dataframe%60-by-column-name-in-python#:~:text=Use%20the%20del%20keyword%20to,the%20name%20column_name%20from%20DataFrame%20.