<a href="https://colab.research.google.com/github/zhi-yu-lin/data-and-python/blob/main/Project_2_Air_quality_mini_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Clean and wrangle air quality data

The following data file contains data collected at a roadside monitoring station.  You can see the data in a spreadsheet here: https://docs.google.com/spreadsheets/d/1XpAvrpuyMsKDO76EZ3kxuddBOu7cZX1Od4uEts14zco/edit?usp=sharing

The data contains:
* a heading line (Chatham Roadside) which needs to be skipped
* dates which are sometimes left- and sometimes right-justified indicating that they are not formatted as dates, rather they are text (so need to be converted to dates)
* times which are not all in the same format
* Nitrogen Dioxide levels which are, again, text and sometimes contain nodata
* Status which is always the same

### Project - clean, sort and wrangle the data

Read the dataset into a dataframe, skipping the first row   
Convert dates to date format  
Remove rows with nodata in the Nitrogen dioxide column  
Convert the Nitrogen dioxide levels values to float type  
Sort by Nitrogen dioxide level  
Create a new column for 'Weekdays' (use df['Date'].dt.weekday)  
Rename the column Nitrogen dioxide level to NO2 Level (V ug/m2)  
Remove the Status column  

The dataset can be viewed here:  https://drive.google.com/file/d/1aYmBf9il2dWA-EROvbYRCZ1rU2t7JwvJ/view?usp=sharing  and the data accessed here: https://drive.google.com/uc?id=1SOe9b4VJ1FCtDVgZ2T8d00-jTw2Kux1i  This is a .csv file  

**NOTE:** Some useful references are included at the bottom of this spreadsheet.

Use the code cell below to work your code.

In [2]:
from datetime import datetime
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scipy.stats

# Read the dataset into a dataframe, skipping the first row
url = 'https://drive.google.com/uc?id=1SOe9b4VJ1FCtDVgZ2T8d00-jTw2Kux1i'
df = pd.read_csv(url, skiprows = 1)
# df.columns = df.iloc[0]
# df = df.drop(0)
df.describe()
df.info()
df

# Convert dates to date format
df['Date'] = pd.to_datetime(df['Date'], format='%d/%m/%Y')

# Remove rows with nodata in the Nitrogen dioxide columnï¼› Convert the Nitrogen dioxide levels values to float type
df['Nitrogen dioxide'] = pd.to_numeric(df['Nitrogen dioxide'], errors='coerce')
df = df.dropna(subset = ['Nitrogen dioxide'])

# Sort by Nitrogen dioxide level
df = df.sort_values(by='Nitrogen dioxide', ascending = False)

# Create a new column for 'Weekdays'
df['Weekdays']= df['Date'].dt.weekday

# Rename the column Nitrogen dioxide level to NO2 Level (V ug/m2)
df.rename(columns={'Nitrogen dioxide': 'NO2 Level (V ug/m2)'}, inplace=True)

# Remove the Status column
df = df.drop(columns=['Status'])
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date              8784 non-null   object
 1   Time              8784 non-null   object
 2   Nitrogen dioxide  8784 non-null   object
 3   Status            8784 non-null   object
dtypes: object(4)
memory usage: 274.6+ KB

           Date   Time  NO2 Level (V ug/m2)  Weekdays
470  2020-01-20  15:00            113.06189         0
6209 2020-09-15  18:00             92.13063         1
6206 2020-09-15  15:00             87.96723         1
808  2020-02-03  17:00             87.10202         0
471  2020-01-20  16:00             84.86896         0
...         ...    ...                  ...       ...
8669 2020-12-27   6:00              0.65300         6
5714 2020-08-26   3:00              0.59123         2
4489 2020-07-06   2:00              0.58930         0
5712 2020-08-26   1:00              0.58689         2
8668 2020-12-27   5:00              0.42410         6

[8632 rows x 4 columns]

### Expand the dataset and show summary statistics for larger dataset
---

There is a second data set here covering the year 2021:  https://drive.google.com/uc?id=1aYmBf9il2dWA-EROvbYRCZ1rU2t7JwvJ  

Concatenate the two datasets to expand it to 2020 and 2021.  

Before you can concatenate the datasets you will need to clean and wrangle the second dataset in the same way as the first.  Use the code cell below.  Give the second dataset a different name.

After the datasets have been concatenated, group the data by Weekdays and show summary statistics by day of the week.

In [13]:
url_2 = 'https://drive.google.com/uc?id=1aYmBf9il2dWA-EROvbYRCZ1rU2t7JwvJ'
df_2 = pd.read_csv(url_2)
df_2.columns = df_2.iloc[0]
df_2 = df_2.drop(0)


df_2['Date'] = pd.to_datetime(df_2['Date'], format='%d/%m/%Y')
df_2['Weekdays']= df_2['Date'].dt.weekday

df_2 = df_2.sort_values(by='Nitrogen dioxide', ascending = False)

df_2.rename(columns={'Nitrogen dioxide': 'NO2 Level (V ug/m2)'}, inplace=True)
df_2 = df_2.drop(columns=['Status'])

summary_by_weekdays = pd.concat([df, df_2], ignore_index=True)
summary_by_weekdays. groupby('Weekdays')['Date'].describe(datetime_is_numeric=True)

,count,mean,min,25%,50%,75%,max
Weekdays,,,,,,,
0,2466,2021-01-03 05:48:36.788321280,2020-01-06 00:00:00,2020-07-06 00:00:00,2021-01-04 00:00:00,2021-07-05 00:00:00,2021-12-27 00:00:00
1,2467,2021-01-04 05:08:11.771382272,2020-01-07 00:00:00,2020-07-07 00:00:00,2021-01-05 00:00:00,2021-07-06 00:00:00,2021-12-28 00:00:00
2,2510,2020-12-30 18:44:27.729083648,2020-01-01 00:00:00,2020-07-01 00:00:00,2020-12-30 00:00:00,2021-06-30 00:00:00,2021-12-29 00:00:00
3,2490,2021-01-01 23:58:15.903614464,2020-01-02 00:00:00,2020-07-02 00:00:00,2021-01-07 00:00:00,2021-07-08 00:00:00,2021-12-30 00:00:00
4,2501,2021-01-02 08:42:47.932826880,2020-01-03 00:00:00,2020-07-03 00:00:00,2021-01-01 00:00:00,2021-07-02 00:00:00,2021-12-31 00:00:00
5,2494,2020-12-29 16:51:00.144346624,2020-01-04 00:00:00,2020-07-04 00:00:00,2021-01-02 00:00:00,2021-07-01 06:00:00,2021-12-25 00:00:00
6,2464,2021-01-01 19:21:49.090909184,2020-01-05 00:00:00,2020-07-05 00:00:00,2021-01-03 00:00:00,2021-07-04 00:00:00,2021-12-26 00:00:00

### Helpful references
---
Skipping rows when reading datasets:  
https://www.geeksforgeeks.org/how-to-skip-rows-while-reading-csv-file-using-pandas/  

Converting strings to dates:  
https://www.geeksforgeeks.org/convert-the-column-type-from-string-to-datetime-format-in-pandas-dataframe/

Dropping rows where data has a given value:  
https://www.datasciencemadesimple.com/drop-delete-rows-conditions-python-pandas/  
(see section Drop a row or observation by condition)

Convert a column of strings to a column of floats:
https://datatofish.com/convert-string-to-float-dataframe/  

Create a new column from data converted in an existing column:  
https://www.geeksforgeeks.org/create-a-new-column-in-pandas-dataframe-based-on-the-existing-columns/  

Rename a column:  
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rename.html  

Remove a column by name:  
https://www.kite.com/python/answers/how-to-delete-columns-from-a-pandas-%60dataframe%60-by-column-name-in-python#:~:text=Use%20the%20del%20keyword%20to,the%20name%20column_name%20from%20DataFrame%20.